import type { SrdClass } from "./types";

export const SRD_CLASSES: SrdClass[] = [
  {
    id: "ID_CLASS_BARBARIAN",
    name: "Barbarian",
    description: "A fierce warrior who can enter a battle rage. While raging, a barbarian gains advantage on Strength checks and saving throws, bonus damage, and resistance to bludgeoning, piercing, and slashing damage.",
    hitDie: 12,
    primaryAbilities: ["str"],
    savingThrows: ["str", "con"],
    armorProficiencies: ["Light", "Medium", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    skillChoices: { from: ["Animal Handling", "Athletics", "Intimidation", "Nature", "Perception", "Survival"], count: 2 },
    subclassUnlockLevel: 3,
    spellcasting: null,
  },
  {
    id: "ID_CLASS_BARD",
    name: "Bard",
    description: "An inspiring magician whose power echoes the music of creation. Bards weave magic through words and music, inspiring allies and hindering foes with spells fueled by Charisma.",
    hitDie: 8,
    primaryAbilities: ["cha"],
    savingThrows: ["dex", "cha"],
    armorProficiencies: ["Light"],
    weaponProficiencies: ["Simple", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
    skillChoices: { from: ["Acrobatics", "Animal Handling", "Arcana", "Athletics", "Deception", "History", "Insight", "Intimidation", "Investigation", "Medicine", "Nature", "Perception", "Performance", "Persuasion", "Religion", "Sleight of Hand", "Stealth", "Survival"], count: 3 },
    subclassUnlockLevel: 3,
    spellcasting: { ability: "cha", startsAtLevel: 1 },
  },
  {
    id: "ID_CLASS_CLERIC",
    name: "Cleric",
    description: "A priestly champion who wields divine magic in service of a higher power. Clerics channel the power of their deity through prayers and spells fueled by Wisdom.",
    hitDie: 8,
    primaryAbilities: ["wis"],
    savingThrows: ["wis", "cha"],
    armorProficiencies: ["Light", "Medium", "Shields"],
    weaponProficiencies: ["Simple"],
    skillChoices: { from: ["History", "Insight", "Medicine", "Persuasion", "Religion"], count: 2 },
    subclassUnlockLevel: 1,
    spellcasting: { ability: "wis", startsAtLevel: 1 },
  },
  {
    id: "ID_CLASS_DRUID",
    name: "Druid",
    description: "A priest of the Old Faith, wielding the powers of nature. Druids cast spells fueled by Wisdom and can transform into beasts using Wild Shape.",
    hitDie: 8,
    primaryAbilities: ["wis"],
    savingThrows: ["int", "wis"],
    armorProficiencies: ["Light", "Medium", "Shields (non-metal)"],
    weaponProficiencies: ["Clubs", "Daggers", "Darts", "Javelins", "Maces", "Quarterstaffs", "Scimitars", "Sickles", "Slings", "Spears"],
    skillChoices: { from: ["Arcana", "Animal Handling", "Insight", "Medicine", "Nature", "Perception", "Religion", "Survival"], count: 2 },
    subclassUnlockLevel: 2,
    spellcasting: { ability: "wis", startsAtLevel: 1 },
  },
  {
    id: "ID_CLASS_FIGHTER",
    name: "Fighter",
    description: "A master of martial combat skilled with a variety of weapons and armor. Fighters choose a Martial Archetype that shapes the nature of their combat style.",
    hitDie: 10,
    primaryAbilities: ["str", "dex"],
    savingThrows: ["str", "con"],
    armorProficiencies: ["Light", "Medium", "Heavy", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    skillChoices: { from: ["Acrobatics", "Animal Handling", "Athletics", "History", "Insight", "Intimidation", "Perception", "Survival"], count: 2 },
    subclassUnlockLevel: 3,
    spellcasting: null,
    asiLevels: [4, 6, 8, 12, 14, 16, 19],
  },
  {
    id: "ID_CLASS_MONK",
    name: "Monk",
    description: "A master of martial arts who harnesses ki — a mystical energy within — to fuel powerful strikes and acrobatic feats. Monks are unarmored and rely on Dexterity and Wisdom.",
    hitDie: 8,
    primaryAbilities: ["dex", "wis"],
    savingThrows: ["str", "dex"],
    armorProficiencies: [],
    weaponProficiencies: ["Simple", "Shortswords"],
    skillChoices: { from: ["Acrobatics", "Athletics", "History", "Insight", "Religion", "Stealth"], count: 2 },
    subclassUnlockLevel: 3,
    spellcasting: null,
  },
  {
    id: "ID_CLASS_PALADIN",
    name: "Paladin",
    description: "A holy warrior bound to a sacred oath. Paladins combine martial prowess with divine spellcasting fueled by Charisma, and can channel divine energy through Divine Smite.",
    hitDie: 10,
    primaryAbilities: ["str", "cha"],
    savingThrows: ["wis", "cha"],
    armorProficiencies: ["Light", "Medium", "Heavy", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    skillChoices: { from: ["Athletics", "Insight", "Intimidation", "Medicine", "Persuasion", "Religion"], count: 2 },
    subclassUnlockLevel: 3,
    spellcasting: { ability: "cha", startsAtLevel: 2 },
  },
  {
    id: "ID_CLASS_RANGER",
    name: "Ranger",
    description: "A warrior who uses martial prowess and nature magic to combat threats on the edges of civilization. Rangers cast spells fueled by Wisdom and choose a favored enemy and terrain.",
    hitDie: 10,
    primaryAbilities: ["dex", "wis"],
    savingThrows: ["str", "dex"],
    armorProficiencies: ["Light", "Medium", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    skillChoices: { from: ["Animal Handling", "Athletics", "Insight", "Investigation", "Nature", "Perception", "Stealth", "Survival"], count: 3 },
    subclassUnlockLevel: 3,
    spellcasting: { ability: "wis", startsAtLevel: 2 },
  },
  {
    id: "ID_CLASS_ROGUE",
    name: "Rogue",
    description: "A scoundrel who uses stealth and trickery to overcome obstacles and enemies. Rogues deal Sneak Attack damage and have Expertise in skills they excel at.",
    hitDie: 8,
    primaryAbilities: ["dex"],
    savingThrows: ["dex", "int"],
    armorProficiencies: ["Light"],
    weaponProficiencies: ["Simple", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
    skillChoices: { from: ["Acrobatics", "Athletics", "Deception", "Insight", "Intimidation", "Investigation", "Perception", "Performance", "Persuasion", "Sleight of Hand", "Stealth"], count: 4 },
    subclassUnlockLevel: 3,
    spellcasting: null,
    asiLevels: [4, 8, 10, 12, 16, 19],
  },
  {
    id: "ID_CLASS_SORCERER",
    name: "Sorcerer",
    description: "A spellcaster who draws on inherent magic from a gift or bloodline. Sorcerers cast spells fueled by Charisma and can manipulate them using Metamagic.",
    hitDie: 6,
    primaryAbilities: ["cha"],
    savingThrows: ["con", "cha"],
    armorProficiencies: [],
    weaponProficiencies: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    skillChoices: { from: ["Arcana", "Deception", "Insight", "Intimidation", "Persuasion", "Religion"], count: 2 },
    subclassUnlockLevel: 1,
    spellcasting: { ability: "cha", startsAtLevel: 1 },
  },
  {
    id: "ID_CLASS_WARLOCK",
    name: "Warlock",
    description: "A wielder of magic derived from a bargain with an extraplanar patron. Warlocks cast spells fueled by Charisma and regain all spell slots on a short rest.",
    hitDie: 8,
    primaryAbilities: ["cha"],
    savingThrows: ["wis", "cha"],
    armorProficiencies: ["Light"],
    weaponProficiencies: ["Simple"],
    skillChoices: { from: ["Arcana", "Deception", "History", "Intimidation", "Investigation", "Nature", "Religion"], count: 2 },
    subclassUnlockLevel: 1,
    spellcasting: { ability: "cha", startsAtLevel: 1 },
  },
  {
    id: "ID_CLASS_WIZARD",
    name: "Wizard",
    description: "A scholarly magic-user capable of manipulating the structures of reality. Wizards cast spells fueled by Intelligence and record spells in a spellbook.",
    hitDie: 6,
    primaryAbilities: ["int"],
    savingThrows: ["int", "wis"],
    armorProficiencies: [],
    weaponProficiencies: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    skillChoices: { from: ["Arcana", "History", "Insight", "Investigation", "Medicine", "Religion"], count: 2 },
    subclassUnlockLevel: 2,
    spellcasting: { ability: "int", startsAtLevel: 1 },
  },
];
