import type { SrdClass } from "./types";

export const SRD_CLASSES: SrdClass[] = [
  {
    id: "ID_CLASS_BARBARIAN",
    name: "Barbarian",
    description: "A fierce warrior who can enter a battle rage. While raging, a barbarian gains advantage on Strength checks and saving throws, bonus damage, and resistance to bludgeoning, piercing, and slashing damage.",
    hitDie: 12,
    primaryAbilities: ["str"],
    savingThrows: ["str", "con"],
    armorProficiencies: ["Light", "Medium", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    skillChoices: { from: ["Animal Handling", "Athletics", "Intimidation", "Nature", "Perception", "Survival"], count: 2 },
    subclassUnlockLevel: 3,
    spellcasting: null,
    featuresByLevel: {
      1:  ["Rage", "Unarmored Defense"],
      2:  ["Reckless Attack", "Danger Sense"],
      3:  ["Primal Path"],
      5:  ["Extra Attack", "Fast Movement"],
      6:  ["Path Feature"],
      7:  ["Feral Instinct"],
      9:  ["Brutal Critical"],
      10: ["Path Feature"],
      11: ["Relentless Rage"],
      13: ["Brutal Critical (2)"],
      14: ["Path Feature"],
      15: ["Persistent Rage"],
      17: ["Brutal Critical (3)"],
      18: ["Indomitable Might"],
      20: ["Primal Champion"],
    },
    featureDescriptions: {
      "Rage":               "As a bonus action, rage for up to 1 minute: advantage on Strength checks and saves, bonus damage on Strength melee attacks (scales with level), and resistance to bludgeoning, piercing, and slashing damage. Uses per long rest increase with level.",
      "Unarmored Defense":  "While not wearing armor, your AC equals 10 + your Dexterity modifier + your Constitution modifier. You may still use a shield.",
      "Reckless Attack":    "When making your first attack on your turn, you can choose to attack recklessly: advantage on all Strength-based melee attack rolls this turn, but attack rolls against you also have advantage until your next turn.",
      "Danger Sense":       "You have advantage on Dexterity saving throws against effects you can see, such as traps and spells, while not blinded, deafened, or incapacitated.",
      "Primal Path":        "You choose a Primal Path, your subclass, that shapes the nature of your rage and grants features at levels 3, 6, 10, and 14.",
      "Extra Attack":       "You can attack twice instead of once whenever you take the Attack action on your turn.",
      "Fast Movement":      "Your speed increases by 10 feet while you aren't wearing heavy armor.",
      "Path Feature":       "Your Primal Path grants you an additional feature.",
      "Feral Instinct":     "You have advantage on Initiative rolls. If surprised, you can act normally on your first turn as long as you enter your rage before doing anything else.",
      "Brutal Critical":    "You roll one additional weapon damage die when determining extra damage for a critical hit with a melee attack.",
      "Relentless Rage":    "When you drop to 0 HP while raging, make a DC 10 Constitution saving throw. On a success, drop to 1 HP instead. The DC rises by 5 each use; resets on a long rest.",
      "Brutal Critical (2)": "You roll two additional weapon damage dice on critical hits with melee attacks.",
      "Persistent Rage":    "Your rage ends early only if you fall unconscious or choose to end it — no longer from not attacking or taking damage.",
      "Brutal Critical (3)": "You roll three additional weapon damage dice on critical hits with melee attacks.",
      "Indomitable Might":  "If your total for a Strength check is less than your Strength score, you can use your Strength score in place of the total.",
      "Primal Champion":    "Your Strength and Constitution scores each increase by 4, and their maximums each increase by 4.",
    },
  },
  {
    id: "ID_CLASS_BARD",
    name: "Bard",
    description: "An inspiring magician whose power echoes the music of creation. Bards weave magic through words and music, inspiring allies and hindering foes with spells fueled by Charisma.",
    hitDie: 8,
    primaryAbilities: ["cha"],
    savingThrows: ["dex", "cha"],
    armorProficiencies: ["Light"],
    weaponProficiencies: ["Simple", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
    skillChoices: { from: ["Acrobatics", "Animal Handling", "Arcana", "Athletics", "Deception", "History", "Insight", "Intimidation", "Investigation", "Medicine", "Nature", "Perception", "Performance", "Persuasion", "Religion", "Sleight of Hand", "Stealth", "Survival"], count: 3 },
    subclassUnlockLevel: 3,
    spellcasting: { ability: "cha", startsAtLevel: 1 },
    featuresByLevel: {
      1:  ["Bardic Inspiration", "Spellcasting"],
      2:  ["Jack of All Trades", "Song of Rest"],
      3:  ["Bard College", "Expertise"],
      5:  ["Font of Inspiration"],
      6:  ["Countercharm", "College Feature"],
      9:  ["Song of Rest (d8)"],
      10: ["Magical Secrets", "Expertise (2)"],
      13: ["Song of Rest (d10)"],
      14: ["College Feature"],
      17: ["Song of Rest (d12)"],
      18: ["Magical Secrets (2)", "College Feature"],
      20: ["Superior Inspiration"],
    },
    featureDescriptions: {
      "Bardic Inspiration":  "As a bonus action, grant a creature within 60 feet a Bardic Inspiration die (d6, scaling with level). They can add it to one ability check, attack roll, or saving throw within 10 minutes. Uses equal to your Charisma modifier per long rest.",
      "Spellcasting":        "You cast bard spells using Charisma as your spellcasting ability. You know a fixed number of spells from the bard list and can replace one known spell each time you gain a bard level.",
      "Jack of All Trades":  "You can add half your proficiency bonus (rounded down) to any ability check that doesn't already use your proficiency bonus.",
      "Song of Rest":        "During a short rest, you perform music or oration. Creatures who hear you regain an extra 1d6 HP when they spend Hit Dice at the end of that rest.",
      "Bard College":        "You delve into the traditions of a Bard College, your subclass, gaining proficiencies and features at levels 3, 6, and 14.",
      "Expertise":           "Choose two skill proficiencies. Your proficiency bonus is doubled for ability checks using those skills.",
      "Font of Inspiration": "You now regain all your Bardic Inspiration uses on a short or long rest, instead of only on a long rest.",
      "Countercharm":        "As an action, begin a performance lasting until the end of your next turn. Friendly creatures within 30 feet have advantage on saving throws against being frightened or charmed.",
      "College Feature":     "Your Bard College grants you an additional feature.",
      "Song of Rest (d8)":   "Your Song of Rest die improves to a d8.",
      "Magical Secrets":     "Choose two spells from any class's spell list. They count as bard spells for you and are added to your spells known.",
      "Expertise (2)":       "Choose two more skill proficiencies to gain doubled proficiency bonus.",
      "Song of Rest (d10)":  "Your Song of Rest die improves to a d10.",
      "Song of Rest (d12)":  "Your Song of Rest die improves to a d12.",
      "Magical Secrets (2)": "Choose two more spells from any class's spell list to add to your spells known.",
      "Superior Inspiration": "When you roll initiative with no Bardic Inspiration uses remaining, you immediately regain one use.",
    },
  },
  {
    id: "ID_CLASS_CLERIC",
    name: "Cleric",
    description: "A priestly champion who wields divine magic in service of a higher power. Clerics channel the power of their deity through prayers and spells fueled by Wisdom.",
    hitDie: 8,
    primaryAbilities: ["wis"],
    savingThrows: ["wis", "cha"],
    armorProficiencies: ["Light", "Medium", "Shields"],
    weaponProficiencies: ["Simple"],
    skillChoices: { from: ["History", "Insight", "Medicine", "Persuasion", "Religion"], count: 2 },
    subclassUnlockLevel: 1,
    spellcasting: { ability: "wis", startsAtLevel: 1 },
    featuresByLevel: {
      1:  ["Spellcasting", "Divine Domain", "Domain Spells"],
      2:  ["Channel Divinity", "Domain Feature"],
      5:  ["Destroy Undead (CR 1/2)"],
      6:  ["Channel Divinity (2)", "Domain Feature"],
      8:  ["Destroy Undead (CR 1)", "Domain Feature"],
      10: ["Divine Intervention"],
      11: ["Destroy Undead (CR 2)"],
      14: ["Destroy Undead (CR 3)"],
      17: ["Destroy Undead (CR 4)", "Domain Feature"],
      18: ["Channel Divinity (3)"],
      20: ["Divine Intervention Improvement"],
    },
    featureDescriptions: {
      "Spellcasting":                    "You cast cleric spells using Wisdom as your spellcasting ability. You prepare a number of spells equal to your Wisdom modifier + your cleric level, choosing from the full cleric spell list.",
      "Divine Domain":                   "You choose a domain tied to your deity's portfolio, shaping your cleric with domain spells, Channel Divinity options, and additional features at higher levels.",
      "Domain Spells":                   "Your domain grants a list of spells that are always prepared. These don't count against the number of spells you can prepare each day.",
      "Channel Divinity":                "You channel divine energy to power magical effects. All clerics can use Turn Undead; your domain grants additional options. One use per short or long rest.",
      "Domain Feature":                  "Your Divine Domain grants you an additional feature.",
      "Destroy Undead (CR 1/2)":         "When an undead of CR 1/2 or lower fails its saving throw against your Turn Undead, it is instantly destroyed rather than just turned.",
      "Channel Divinity (2)":            "You can use Channel Divinity twice between short or long rests.",
      "Destroy Undead (CR 1)":           "Your Turn Undead now instantly destroys undead of CR 1 or lower on a failed save.",
      "Divine Intervention":             "As an action, implore your deity for aid. Roll d100; if the result ≤ your cleric level, your deity intervenes with an effect of their choosing. Once per long rest (seven days if successful).",
      "Destroy Undead (CR 2)":           "Your Turn Undead now instantly destroys undead of CR 2 or lower on a failed save.",
      "Destroy Undead (CR 3)":           "Your Turn Undead now instantly destroys undead of CR 3 or lower on a failed save.",
      "Destroy Undead (CR 4)":           "Your Turn Undead now instantly destroys undead of CR 4 or lower on a failed save.",
      "Channel Divinity (3)":            "You can use Channel Divinity three times between short or long rests.",
      "Divine Intervention Improvement": "Your deity always answers when you use Divine Intervention — no roll required.",
    },
  },
  {
    id: "ID_CLASS_DRUID",
    name: "Druid",
    description: "A priest of the Old Faith, wielding the powers of nature. Druids cast spells fueled by Wisdom and can transform into beasts using Wild Shape.",
    hitDie: 8,
    primaryAbilities: ["wis"],
    savingThrows: ["int", "wis"],
    armorProficiencies: ["Light", "Medium", "Shields (non-metal)"],
    weaponProficiencies: ["Clubs", "Daggers", "Darts", "Javelins", "Maces", "Quarterstaffs", "Scimitars", "Sickles", "Slings", "Spears"],
    skillChoices: { from: ["Arcana", "Animal Handling", "Insight", "Medicine", "Nature", "Perception", "Religion", "Survival"], count: 2 },
    subclassUnlockLevel: 2,
    spellcasting: { ability: "wis", startsAtLevel: 1 },
    featuresByLevel: {
      1:  ["Druidic", "Spellcasting"],
      2:  ["Wild Shape", "Druid Circle"],
      4:  ["Wild Shape Improvement"],
      6:  ["Circle Feature"],
      8:  ["Wild Shape Improvement (2)"],
      10: ["Circle Feature"],
      14: ["Circle Feature"],
      18: ["Timeless Body", "Beast Spells"],
      20: ["Archdruid"],
    },
    featureDescriptions: {
      "Druidic":                    "You know the secret Druidic language. You can speak it and use it to leave hidden messages; non-druids automatically fail to notice them.",
      "Spellcasting":               "You cast druid spells using Wisdom as your spellcasting ability. You prepare a number of spells equal to your Wisdom modifier + your druid level from the full druid spell list.",
      "Wild Shape":                 "As an action, magically transform into a beast you have seen. CR limit and allowed speeds increase with level. You retain mental stats and class features but gain the beast's physical stats. Two uses per short or long rest.",
      "Druid Circle":               "You align yourself with a circle of druids, your subclass, granting features at levels 2, 6, 10, and 14.",
      "Wild Shape Improvement":     "You can now transform into beasts of CR 1/2 or lower, including those with a swim speed.",
      "Circle Feature":             "Your Druid Circle grants you an additional feature.",
      "Wild Shape Improvement (2)": "You can now transform into beasts of CR 1 or lower, including those with a fly speed.",
      "Timeless Body":              "Your druidic magic grants immunity to aging effects, and you age at one-tenth the normal rate.",
      "Beast Spells":               "While in Wild Shape form, you can cast druid spells that have no material components.",
      "Archdruid":                  "You can use Wild Shape an unlimited number of times. You may also ignore verbal, somatic, and non-costly material components of druid spells.",
    },
  },
  {
    id: "ID_CLASS_FIGHTER",
    name: "Fighter",
    description: "A master of martial combat skilled with a variety of weapons and armor. Fighters choose a Martial Archetype that shapes the nature of their combat style.",
    hitDie: 10,
    primaryAbilities: ["str", "dex"],
    savingThrows: ["str", "con"],
    armorProficiencies: ["Light", "Medium", "Heavy", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    skillChoices: { from: ["Acrobatics", "Animal Handling", "Athletics", "History", "Insight", "Intimidation", "Perception", "Survival"], count: 2 },
    subclassUnlockLevel: 3,
    spellcasting: null,
    asiLevels: [4, 6, 8, 12, 14, 16, 19],
    featuresByLevel: {
      1:  ["Fighting Style", "Second Wind"],
      2:  ["Action Surge"],
      3:  ["Martial Archetype"],
      5:  ["Extra Attack"],
      7:  ["Martial Archetype Feature"],
      9:  ["Indomitable"],
      10: ["Martial Archetype Feature"],
      11: ["Extra Attack (2)"],
      13: ["Indomitable (2)"],
      15: ["Martial Archetype Feature"],
      17: ["Action Surge (2)", "Indomitable (3)"],
      18: ["Martial Archetype Feature"],
      20: ["Extra Attack (3)"],
    },
    featureDescriptions: {
      "Fighting Style":      "You adopt a particular style of fighting as your specialty. Choose one option. You can't take a Fighting Style option more than once.",
      "Second Wind":         "As a bonus action, regain HP equal to 1d10 + your fighter level. Recharges on a short or long rest.",
      "Action Surge":        "On your turn, take one additional action on top of your regular action. Recharges on a short or long rest.",
      "Martial Archetype":   "You choose an archetype that you strive to emulate in your combat style and techniques, shaping how you fight at higher levels.",
      "Extra Attack":        "You can attack twice instead of once whenever you take the Attack action on your turn.",
      "Extra Attack (2)":    "You can attack three times whenever you take the Attack action on your turn.",
      "Extra Attack (3)":    "You can attack four times whenever you take the Attack action on your turn.",
      "Indomitable":         "You can reroll a saving throw that you fail. You must use the new roll. Once per long rest.",
      "Indomitable (2)":     "You can use Indomitable twice between long rests.",
      "Indomitable (3)":     "You can use Indomitable three times between long rests.",
      "Action Surge (2)":    "You can use Action Surge twice before needing a rest.",
      "Martial Archetype Feature": "Your Martial Archetype grants you a new feature.",
    },
  },
  {
    id: "ID_CLASS_MONK",
    name: "Monk",
    description: "A master of martial arts who harnesses ki — a mystical energy within — to fuel powerful strikes and acrobatic feats. Monks are unarmored and rely on Dexterity and Wisdom.",
    hitDie: 8,
    primaryAbilities: ["dex", "wis"],
    savingThrows: ["str", "dex"],
    armorProficiencies: [],
    weaponProficiencies: ["Simple", "Shortswords"],
    skillChoices: { from: ["Acrobatics", "Athletics", "History", "Insight", "Religion", "Stealth"], count: 2 },
    subclassUnlockLevel: 3,
    spellcasting: null,
    featuresByLevel: {
      1:  ["Unarmored Defense", "Martial Arts"],
      2:  ["Ki", "Unarmored Movement"],
      3:  ["Monastic Tradition", "Deflect Missiles"],
      4:  ["Slow Fall"],
      5:  ["Extra Attack", "Stunning Strike"],
      6:  ["Ki-Empowered Strikes", "Tradition Feature"],
      7:  ["Evasion", "Stillness of Mind"],
      9:  ["Unarmored Movement Improvement"],
      10: ["Purity of Body", "Tradition Feature"],
      11: ["Tongue of the Sun and Moon"],
      13: ["Diamond Soul"],
      14: ["Timeless Body"],
      15: ["Empty Body", "Tradition Feature"],
      18: ["Tradition Feature"],
      20: ["Perfect Self"],
    },
    featureDescriptions: {
      "Unarmored Defense":            "While not wearing armor or wielding a shield, your AC equals 10 + your Dexterity modifier + your Wisdom modifier.",
      "Martial Arts":                 "Your unarmed strikes and monk weapons deal a martial arts die (d4, scaling with level). You can use Dexterity for their attack and damage rolls, and you can make one unarmed strike as a bonus action after attacking with an unarmed strike or monk weapon.",
      "Ki":                           "You have ki points equal to your monk level. Spend them to use Flurry of Blows (2 unarmed strikes as a bonus action), Patient Defense (Dodge as a bonus action), or Step of the Wind (Dash or Disengage as a bonus action). Regain all ki on a short or long rest.",
      "Unarmored Movement":           "Your speed increases by 10 feet while not wearing armor or wielding a shield. This bonus improves at levels 9, 13, and 17.",
      "Monastic Tradition":           "You commit to a Monastic Tradition, your subclass, granting features at levels 3, 6, 11, and 17.",
      "Deflect Missiles":             "As a reaction when hit by a ranged weapon attack, reduce the damage by 1d10 + Dexterity modifier + monk level. If reduced to 0, you can spend 1 ki to catch and throw the missile as a ranged attack.",
      "Slow Fall":                    "As a reaction when you fall, reduce the falling damage you take by 5 × your monk level.",
      "Extra Attack":                 "You can attack twice instead of once whenever you take the Attack action on your turn.",
      "Stunning Strike":              "When you hit a creature with a melee weapon attack, spend 1 ki point to force a Constitution saving throw. On a failure, the creature is stunned until the end of your next turn.",
      "Ki-Empowered Strikes":         "Your unarmed strikes count as magical for the purpose of overcoming resistance and immunity to nonmagical attacks.",
      "Tradition Feature":            "Your Monastic Tradition grants you an additional feature.",
      "Evasion":                      "When subjected to an effect that allows a Dexterity saving throw for half damage, you take no damage on a success and only half on a failure.",
      "Stillness of Mind":            "As an action, end one effect on yourself causing you to be charmed or frightened.",
      "Unarmored Movement Improvement": "You can now move along vertical surfaces and across liquids without falling, as long as you end your movement on a horizontal surface.",
      "Purity of Body":               "Your mastery of ki makes you immune to disease and poison.",
      "Tongue of the Sun and Moon":   "You can understand all spoken languages, and any creature that speaks at least one language can understand you.",
      "Diamond Soul":                 "You are proficient in all saving throws. When you fail a saving throw, you can spend 1 ki point to reroll it and must use the new result.",
      "Timeless Body":                "Your ki sustains you so you suffer no frailty from old age and can't be aged magically. You also no longer need food or water.",
      "Empty Body":                   "Spend 4 ki points to become invisible for 1 minute with resistance to all damage except force. Spend 8 ki points to cast astral projection on yourself without a silver cord.",
      "Perfect Self":                 "When you roll initiative with no ki points remaining, you regain 4 ki points.",
    },
  },
  {
    id: "ID_CLASS_PALADIN",
    name: "Paladin",
    description: "A holy warrior bound to a sacred oath. Paladins combine martial prowess with divine spellcasting fueled by Charisma, and can channel divine energy through Divine Smite.",
    hitDie: 10,
    primaryAbilities: ["str", "cha"],
    savingThrows: ["wis", "cha"],
    armorProficiencies: ["Light", "Medium", "Heavy", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    skillChoices: { from: ["Athletics", "Insight", "Intimidation", "Medicine", "Persuasion", "Religion"], count: 2 },
    subclassUnlockLevel: 3,
    spellcasting: { ability: "cha", startsAtLevel: 2 },
    featuresByLevel: {
      1:  ["Divine Sense", "Lay on Hands"],
      2:  ["Fighting Style", "Spellcasting", "Divine Smite"],
      3:  ["Divine Health", "Sacred Oath", "Channel Divinity"],
      5:  ["Extra Attack"],
      6:  ["Aura of Protection"],
      7:  ["Sacred Oath Feature"],
      10: ["Aura of Courage"],
      11: ["Improved Divine Smite"],
      14: ["Cleansing Touch"],
      15: ["Sacred Oath Feature"],
      18: ["Aura Improvements"],
      20: ["Sacred Oath Feature"],
    },
    featureDescriptions: {
      "Divine Sense":           "As an action, know the location of any celestial, fiend, or undead within 60 feet that isn't behind total cover. Usable 1 + Charisma modifier times per long rest.",
      "Lay on Hands":           "Touch a creature to restore HP from a pool equal to 5 × your paladin level. You can also spend 5 HP from the pool to cure a disease or neutralize one poison. Recharges on a long rest.",
      "Fighting Style":         "You adopt a particular style of fighting as your specialty. Choose one option from the Paladin list (Defense, Dueling, Great Weapon Fighting, or Protection).",
      "Spellcasting":           "You can cast paladin spells using Charisma as your spellcasting ability. You prepare spells from the paladin list equal to your Charisma modifier + half your paladin level.",
      "Divine Smite":           "When you hit a creature with a melee weapon attack, you can expend one spell slot to deal 2d8 radiant damage plus 1d8 per spell slot level above 1st. Damage increases by 1d8 against undead or fiends.",
      "Divine Health":          "Your divine magic grants you immunity to disease.",
      "Sacred Oath":            "You swear the oath that binds you as a paladin forever, choosing your subclass and gaining its oath spells and Channel Divinity options.",
      "Channel Divinity":       "You can channel divine energy to fuel magical effects granted by your Sacred Oath. You have one use, regained on a short or long rest.",
      "Extra Attack":           "You can attack twice instead of once whenever you take the Attack action on your turn.",
      "Aura of Protection":     "While you are conscious, you and friendly creatures within 10 feet of you add your Charisma modifier (minimum +1) to all saving throws.",
      "Sacred Oath Feature":    "Your Sacred Oath grants you an additional feature.",
      "Aura of Courage":        "While you are conscious, you and friendly creatures within 10 feet of you can't be frightened.",
      "Improved Divine Smite":  "Your melee weapon attacks deal an additional 1d8 radiant damage on every hit, stacking with any Divine Smite you use.",
      "Cleansing Touch":        "As an action, end one spell affecting a willing creature you touch. Usable a number of times equal to your Charisma modifier per long rest.",
      "Aura Improvements":      "Your Aura of Protection and Aura of Courage now extend to 30 feet instead of 10.",
      "Paladin's Smite":        "When you hit with a melee weapon or Unarmed Strike, you can expend a spell slot to deal extra Radiant damage: 2d8 for a 1st-level slot, plus 1d8 per slot level above 1st (maximum 5d8). The damage increases by 1d8 against Undead or Fiends. On a critical hit, one of the dice is doubled.",
      "Faithful Steed":         "You can cast Find Steed without expending a spell slot. The steed gains immunity to the Charmed and Frightened conditions.",
      "Abjure Foes":            "As a Magic action, expend one use of Channel Divinity to awe creatures you can see within 60 feet. Each target must succeed on a Wisdom saving throw or be Frightened of you for 1 minute or until it takes any damage.",
      "Radiant Strikes":        "Your melee weapon attacks and Unarmed Strikes deal an extra 1d8 Radiant damage on each hit.",
      "Restoring Touch":        "When you use Lay on Hands on a creature, you can also remove one of the following conditions from it: Blinded, Charmed, Deafened, Frightened, Paralyzed, or Stunned.",
      "Aura Expansion":         "Your Aura of Protection now extends 30 feet from you instead of 10 feet.",
      "Epic Boon":              "You gain an Epic Boon feat, or another feat of your choice for which you qualify. Boon of Truesight is recommended.",
    },
  },
  {
    id: "ID_CLASS_RANGER",
    name: "Ranger",
    description: "A warrior who uses martial prowess and nature magic to combat threats on the edges of civilization. Rangers cast spells fueled by Wisdom and choose a favored enemy and terrain.",
    hitDie: 10,
    primaryAbilities: ["dex", "wis"],
    savingThrows: ["str", "dex"],
    armorProficiencies: ["Light", "Medium", "Shields"],
    weaponProficiencies: ["Simple", "Martial"],
    skillChoices: { from: ["Animal Handling", "Athletics", "Insight", "Investigation", "Nature", "Perception", "Stealth", "Survival"], count: 3 },
    subclassUnlockLevel: 3,
    spellcasting: { ability: "wis", startsAtLevel: 2 },
    featuresByLevel: {
      1:  ["Favored Enemy", "Natural Explorer"],
      2:  ["Fighting Style", "Spellcasting"],
      3:  ["Ranger Archetype", "Primeval Awareness"],
      5:  ["Extra Attack"],
      6:  ["Favored Enemy (2)", "Natural Explorer (2)"],
      7:  ["Ranger Archetype Feature"],
      8:  ["Land's Stride"],
      10: ["Hide in Plain Sight", "Natural Explorer (3)"],
      11: ["Ranger Archetype Feature"],
      14: ["Vanish", "Favored Enemy (3)"],
      15: ["Ranger Archetype Feature"],
      18: ["Feral Senses"],
      20: ["Foe Slayer"],
    },
  },
  {
    id: "ID_CLASS_ROGUE",
    name: "Rogue",
    description: "A scoundrel who uses stealth and trickery to overcome obstacles and enemies. Rogues deal Sneak Attack damage and have Expertise in skills they excel at.",
    hitDie: 8,
    primaryAbilities: ["dex"],
    savingThrows: ["dex", "int"],
    armorProficiencies: ["Light"],
    weaponProficiencies: ["Simple", "Hand Crossbows", "Longswords", "Rapiers", "Shortswords"],
    skillChoices: { from: ["Acrobatics", "Athletics", "Deception", "Insight", "Intimidation", "Investigation", "Perception", "Performance", "Persuasion", "Sleight of Hand", "Stealth"], count: 4 },
    subclassUnlockLevel: 3,
    spellcasting: null,
    asiLevels: [4, 8, 10, 12, 16, 19],
    featuresByLevel: {
      1:  ["Expertise", "Sneak Attack", "Thieves' Cant"],
      2:  ["Cunning Action"],
      3:  ["Roguish Archetype"],
      5:  ["Uncanny Dodge"],
      6:  ["Expertise (2)"],
      7:  ["Evasion"],
      9:  ["Roguish Archetype Feature"],
      11: ["Reliable Talent"],
      13: ["Roguish Archetype Feature"],
      14: ["Blindsense"],
      15: ["Slippery Mind"],
      17: ["Roguish Archetype Feature"],
      18: ["Elusive"],
      20: ["Stroke of Luck"],
    },
  },
  {
    id: "ID_CLASS_SORCERER",
    name: "Sorcerer",
    description: "A spellcaster who draws on inherent magic from a gift or bloodline. Sorcerers cast spells fueled by Charisma and can manipulate them using Metamagic.",
    hitDie: 6,
    primaryAbilities: ["cha"],
    savingThrows: ["con", "cha"],
    armorProficiencies: [],
    weaponProficiencies: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    skillChoices: { from: ["Arcana", "Deception", "Insight", "Intimidation", "Persuasion", "Religion"], count: 2 },
    subclassUnlockLevel: 1,
    spellcasting: { ability: "cha", startsAtLevel: 1 },
    featuresByLevel: {
      1:  ["Spellcasting", "Sorcerous Origin"],
      2:  ["Font of Magic"],
      3:  ["Metamagic"],
      6:  ["Sorcerous Origin Feature"],
      10: ["Metamagic (2)"],
      14: ["Sorcerous Origin Feature"],
      17: ["Metamagic (3)"],
      18: ["Sorcerous Origin Feature"],
      20: ["Sorcerous Restoration"],
    },
  },
  {
    id: "ID_CLASS_WARLOCK",
    name: "Warlock",
    description: "A wielder of magic derived from a bargain with an extraplanar patron. Warlocks cast spells fueled by Charisma and regain all spell slots on a short rest.",
    hitDie: 8,
    primaryAbilities: ["cha"],
    savingThrows: ["wis", "cha"],
    armorProficiencies: ["Light"],
    weaponProficiencies: ["Simple"],
    skillChoices: { from: ["Arcana", "Deception", "History", "Intimidation", "Investigation", "Nature", "Religion"], count: 2 },
    subclassUnlockLevel: 1,
    spellcasting: { ability: "cha", startsAtLevel: 1 },
    featuresByLevel: {
      1:  ["Otherworldly Patron", "Pact Magic"],
      2:  ["Eldritch Invocations"],
      3:  ["Pact Boon"],
      6:  ["Otherworldly Patron Feature"],
      10: ["Otherworldly Patron Feature"],
      11: ["Mystic Arcanum (6th level)"],
      13: ["Mystic Arcanum (7th level)"],
      14: ["Otherworldly Patron Feature"],
      15: ["Mystic Arcanum (8th level)"],
      17: ["Mystic Arcanum (9th level)"],
      20: ["Eldritch Master"],
    },
  },
  {
    id: "ID_CLASS_WIZARD",
    name: "Wizard",
    description: "A scholarly magic-user capable of manipulating the structures of reality. Wizards cast spells fueled by Intelligence and record spells in a spellbook.",
    hitDie: 6,
    primaryAbilities: ["int"],
    savingThrows: ["int", "wis"],
    armorProficiencies: [],
    weaponProficiencies: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light Crossbows"],
    skillChoices: { from: ["Arcana", "History", "Insight", "Investigation", "Medicine", "Religion"], count: 2 },
    subclassUnlockLevel: 2,
    spellcasting: { ability: "int", startsAtLevel: 1 },
    featuresByLevel: {
      1:  ["Spellcasting", "Arcane Recovery"],
      2:  ["Arcane Tradition"],
      6:  ["Arcane Tradition Feature"],
      10: ["Arcane Tradition Feature"],
      14: ["Arcane Tradition Feature"],
      18: ["Spell Mastery"],
      20: ["Signature Spells"],
    },
  },
];
