// Feature registry — the canonical map from FeatureDef.id to FeatureDef.
//
// Chunk 1 lands the empty map. Subsequent chunks add migration consumers
// (deriveStats walks effects, level-up panel walks choices, etc.) and then
// chunk 9 populates the registry one class per commit.
//
// Lookup helpers live here so consumers don't reach into the map directly.

import type { FeatureDef } from "./types";
import { FEAT_ALERT, FEAT_INSPIRING_LEADER, FEAT_LUCKY, FEAT_TOUGH } from "./data/feats";
import { CHAMPION_EXTRA_FIGHTING_STYLE, SUBCLASS_CHAMPION_REMARKABLE_ATHLETE } from "./data/subclasses";
import {
  BARBARIAN_RAGE,
  BARBARIAN_UNARMORED_DEFENSE,
  BARBARIAN_WEAPON_MASTERY,
  BARBARIAN_DANGER_SENSE,
  BARBARIAN_RECKLESS_ATTACK,
  BARBARIAN_PRIMAL_KNOWLEDGE,
  BARBARIAN_EXTRA_ATTACK,
  BARBARIAN_FAST_MOVEMENT,
  BARBARIAN_FERAL_INSTINCT,
  BARBARIAN_INSTINCTIVE_POUNCE,
  BARBARIAN_BRUTAL_STRIKE,
  BARBARIAN_RELENTLESS_RAGE,
  BARBARIAN_IMPROVED_BRUTAL_STRIKE,
  BARBARIAN_PERSISTENT_RAGE,
  BARBARIAN_IMPROVED_BRUTAL_STRIKE_L17,
  BARBARIAN_INDOMITABLE_MIGHT,
  BARBARIAN_PRIMAL_CHAMPION,
} from "./data/classes/barbarian";
import { BARDIC_INSPIRATION } from "./data/classes/bard";
import { CLERIC_CHANNEL_DIVINITY } from "./data/classes/cleric";
import { WILD_SHAPE } from "./data/classes/druid";
import {
  ACTION_SURGE,
  FIGHTER_FIGHTING_STYLE,
  FIGHTER_INDOMITABLE,
  FIGHTER_INDOMITABLE_2,
  FIGHTER_INDOMITABLE_3,
  FIGHTER_EXTRA_ATTACK,
  FIGHTER_TACTICAL_MIND,
  FIGHTER_TACTICAL_SHIFT,
  FIGHTER_THREE_EXTRA_ATTACKS,
  FIGHTER_TWO_EXTRA_ATTACKS,
  FIGHTER_WEAPON_MASTERY,
  SECOND_WIND,
} from "./data/classes/fighter";
import {
  FEAT_FIGHTING_STYLE_ARCHERY,
  FEAT_FIGHTING_STYLE_DEFENSE,
  FEAT_FIGHTING_STYLE_DUELING,
  FEAT_FIGHTING_STYLE_GREAT_WEAPON_FIGHTING,
  FEAT_FIGHTING_STYLE_PROTECTION,
  FEAT_FIGHTING_STYLE_TWO_WEAPON_FIGHTING,
} from "./data/feats-fighting-styles";
import {
  KI_POINTS,
  MONK_ACROBATIC_MOVEMENT,
  MONK_BODY_AND_MIND,
  MONK_DEFLECT_ATTACKS,
  MONK_DEFLECT_ENERGY,
  MONK_DISCIPLINED_SURVIVOR,
  MONK_EMPTY_BODY,
  MONK_EVASION,
  MONK_EXTRA_ATTACK,
  MONK_FLURRY_OF_BLOWS,
  MONK_KI_EMPOWERED_STRIKES,
  MONK_MARTIAL_ARTS,
  MONK_PATIENT_DEFENSE,
  MONK_PERFECT_FOCUS,
  MONK_SELF_RESTORATION,
  MONK_SLOW_FALL,
  MONK_STEP_OF_THE_WIND,
  MONK_STILLNESS_OF_MIND,
  MONK_STUNNING_STRIKE,
  MONK_SUPERIOR_DEFENSE,
  MONK_TONGUE_OF_SUN_AND_MOON,
  MONK_UNARMORED_DEFENSE,
  MONK_UNARMORED_MOVEMENT,
} from "./data/classes/monk";
import { LAY_ON_HANDS, PALADIN_CHANNEL_DIVINITY, PALADIN_FIGHTING_STYLE, PALADIN_AURA_OF_PROTECTION, PALADIN_AURA_EXPANSION } from "./data/classes/paladin";
import { RANGER_FIGHTING_STYLE } from "./data/classes/ranger";
import { SORCERY_POINTS } from "./data/classes/sorcerer";
import { ARCANE_RECOVERY } from "./data/classes/wizard";
import { ALL_ASI_DEFS } from "./data/asi-choices";

const BASE_DEFS: FeatureDef[] = [
  FEAT_TOUGH,
  FEAT_ALERT,
  FEAT_LUCKY,
  FEAT_INSPIRING_LEADER,
  CHAMPION_EXTRA_FIGHTING_STYLE,
  SUBCLASS_CHAMPION_REMARKABLE_ATHLETE,
  BARBARIAN_RAGE,
  BARBARIAN_UNARMORED_DEFENSE,
  BARBARIAN_WEAPON_MASTERY,
  BARBARIAN_DANGER_SENSE,
  BARBARIAN_RECKLESS_ATTACK,
  BARBARIAN_PRIMAL_KNOWLEDGE,
  BARBARIAN_EXTRA_ATTACK,
  BARBARIAN_FAST_MOVEMENT,
  BARBARIAN_FERAL_INSTINCT,
  BARBARIAN_INSTINCTIVE_POUNCE,
  BARBARIAN_BRUTAL_STRIKE,
  BARBARIAN_RELENTLESS_RAGE,
  BARBARIAN_IMPROVED_BRUTAL_STRIKE,
  BARBARIAN_PERSISTENT_RAGE,
  BARBARIAN_IMPROVED_BRUTAL_STRIKE_L17,
  BARBARIAN_INDOMITABLE_MIGHT,
  BARBARIAN_PRIMAL_CHAMPION,
  BARDIC_INSPIRATION,
  CLERIC_CHANNEL_DIVINITY,
  WILD_SHAPE,
  FIGHTER_FIGHTING_STYLE,
  ACTION_SURGE,
  SECOND_WIND,
  FIGHTER_WEAPON_MASTERY,
  FIGHTER_TACTICAL_MIND,
  FIGHTER_EXTRA_ATTACK,
  FIGHTER_INDOMITABLE,
  FIGHTER_TACTICAL_SHIFT,
  FIGHTER_TWO_EXTRA_ATTACKS,
  FIGHTER_INDOMITABLE_2,
  FIGHTER_INDOMITABLE_3,
  FIGHTER_THREE_EXTRA_ATTACKS,
  FEAT_FIGHTING_STYLE_ARCHERY,
  FEAT_FIGHTING_STYLE_DEFENSE,
  FEAT_FIGHTING_STYLE_DUELING,
  FEAT_FIGHTING_STYLE_GREAT_WEAPON_FIGHTING,
  FEAT_FIGHTING_STYLE_PROTECTION,
  FEAT_FIGHTING_STYLE_TWO_WEAPON_FIGHTING,
  KI_POINTS,
  MONK_MARTIAL_ARTS,
  MONK_UNARMORED_DEFENSE,
  MONK_UNARMORED_MOVEMENT,
  MONK_FLURRY_OF_BLOWS,
  MONK_PATIENT_DEFENSE,
  MONK_STEP_OF_THE_WIND,
  MONK_DEFLECT_ATTACKS,
  MONK_SLOW_FALL,
  MONK_EXTRA_ATTACK,
  MONK_STUNNING_STRIKE,
  MONK_KI_EMPOWERED_STRIKES,
  MONK_EVASION,
  MONK_STILLNESS_OF_MIND,
  MONK_ACROBATIC_MOVEMENT,
  MONK_SELF_RESTORATION,
  MONK_TONGUE_OF_SUN_AND_MOON,
  MONK_DEFLECT_ENERGY,
  MONK_DISCIPLINED_SURVIVOR,
  MONK_EMPTY_BODY,
  MONK_PERFECT_FOCUS,
  MONK_SUPERIOR_DEFENSE,
  MONK_BODY_AND_MIND,
  LAY_ON_HANDS,
  PALADIN_CHANNEL_DIVINITY,
  PALADIN_FIGHTING_STYLE,
  PALADIN_AURA_OF_PROTECTION,
  PALADIN_AURA_EXPANSION,
  RANGER_FIGHTING_STYLE,
  SORCERY_POINTS,
  ARCANE_RECOVERY,
  ...ALL_ASI_DEFS,
];

export const FEATURE_REGISTRY: Record<string, FeatureDef> = Object.fromEntries(
  BASE_DEFS.map((d) => [d.id, d])
);

/** Resolve a feature by canonical ID. Returns undefined if absent. */
export function getFeatureDef(id: string): FeatureDef | undefined {
  return FEATURE_REGISTRY[id];
}

/** All registered features. Order is insertion order. */
export function allFeatureDefs(): FeatureDef[] {
  return Object.values(FEATURE_REGISTRY);
}
